### ISSUE TITLE
setting path d not working

### ISSUE THREAD

**Issue by cylzh** [d3/d3-transition#60]
````
<svg id="test" width="500" height="500">

    <path ></path>
</svg>

````
````
 d3.selectAll("#test path").transition(t).style("stroke","red").attr("d",function(){
        return "M0,0L20,20"
    })
````

**Comment by mbostock** [comment]
You haven’t included any information about what you expected to happen, and how the observed behavior differed from what you expected. The expected behavior when interpolating from the empty string (the default *d* attribute on a path element) to a non-empty string is just the non-empty string. If you want some different behavior, you’ll need to initialize the path element’s *d* attribute to a different value, or use a different interpolator in place of the default d3.interpolateString.

Please use [Stack Overflow tag d3.js](https://stackoverflow.com/tags/d3.js) to ask for help. Although I make an effort to assist everyone that asks, I am not always available to provide help promptly or directly. Stack Overflow provides a better collaborative forum for self-help: tens of thousands of D3-related questions have already been asked there, and some answered questions may be relevant to you.

When asking for help, please include a link to a live example that demonstrates the issue, preferably on [bl.ocks.org](http://bl.ocks.org). It is often impossible to debug from code snippets alone. Isolate the issue and reduce your code as much as possible before asking for help. The less code you post, the easier it is for someone to debug, and the more likely you are to get a helpful response.

If you have a question about D3’s behavior and want to discuss it with other users, also consider the [d3-js Google Group](https://groups.google.com/forum/#!forum/d3-js) or [joining](https://d3-slackin.herokuapp.com/) the [d3-js Slack](https://d3js.slack.com/).

Thank you! 🤗
