### ISSUE TITLE
Window is not a function

### ISSUE THREAD

**Issue by miroli** [d3/d3-transition#62]
Whenever I try to use transitions in d3 v. 4 I get this error:

    Uncaught TypeError: window is not a function(…)

It references [this line](https://github.com/d3/d3-transition/blob/f2e6c9598a21238bfb7031ea0f1e82822f14d4eb/src/transition/style.js#L11). I'm using rollup to write ES6 modules and this is the entirety of my code:

    import { transition } from 'd3-transition';
    import { select, selectAll } from 'd3-selection';
    
    selectAll('h1').transition().style('color', '#fff');

**Comment by mbostock** [comment]
It sounds like the global `window` is not available in your environment. I’d probably start investigating by trying `select(document.body).selectAll('h1')` and seeing if that works, debugging your environment from there. But without being able to reproduce your environment, I can’t speculate as to why `window` would not have the expected value. If you can post an example on bl.ocks.org that demonstrates the issue I can investigate further.

**Comment by mbostock** [comment]
Oops, on mobile and didn’t click the linked line before replying. If the imported `window` is not defined, I’d guess either there is a problem resolving the d3-selection module (or maybe the wrong version?) or there might be a bug in Rollup, say where it is incorrectly eliminating the `window` definition because it thinks it isn’t used. But again you’ll have to post a reproduction of your environment so I can see what exactly is going on (including the exact versions of the code and Rollup etc.) if you want me to investigate.

**Comment by miroli** [comment]
I created a simplified version of my environment, which suffers from the same error.

https://github.com/miroli/transition-debugging

**Comment by mbostock** [comment]
There are two bugs here, one of which is definitely Rollup, and the other of which is either in your configuration or in Rollup.

1. Newer versions of Rollup are using `var foo = …` to declare symbols, which breaks hosting. It looks like 0.34 is the latest version that works.

2. You’re specifying the output format `es` but I think you want `iife`. If you use `es`, the symbols appear to be defined in the global scope, which means you’ll end up with `function window(…) { … }` which will throw an error.

**Comment by miroli** [comment]
Thank you very much! That did indeed solve the problem.
