### ISSUE TITLE
How to use transition with timer?

### ISSUE THREAD

**Issue by moroshko** [d3/d3-transition#65]
@mbostock It would be great to collect your thoughts on this one:
http://stackoverflow.com/q/41800541/247243

[The proposed solution](http://stackoverflow.com/a/41817668/247243) feels somewhat hacky. 
I wonder if we can use [`d3.active()`](https://github.com/d3/d3-transition/blob/master/README.md#active) to solve this?

**Comment by mbostock** [comment]
Please use Stack Overflow to ask for help.

Also, it looks like you are starting a transition inside a timer callback, which means you are starting a new transition 60 times a second. Not sure what you are trying to accomplish.

**Comment by mbostock** [comment]
Here’s a “fixed” version of your code:

https://bl.ocks.org/mbostock/a29e1eeb2bb15c97663dd336cd13f121

But, I still wouldn’t recommend this approach because you’re doing a lot of needless work on every tick of the timer. It’d be better to do that work only when the data changes (*i.e.*, when the button is pressed).

Based solely on what you’ve shared, I’d do something like this, where you create a short-lived transition for each entering circle on click, and the transition cleans itself up when the circle is no longer needed:

https://bl.ocks.org/mbostock/ad550c9d6d156ac726b45f48fa6ff2c7

**Comment by moroshko** [comment]
Thanks Mike, this is much more helpful than the previous response 👍
